name: Build otomatis 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.0
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: '13114758'
        packages: 'platforms;android-36.1 build-tools;36.1.0 platform-tools'

    - name: Install NDK
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --channel=0 --install "ndk;28.2.13676358"
        echo "NDK_HOME=$ANDROID_HOME/ndk/28.2.13676358" >> $GITHUB_ENV

    - name: Fix Gradle Wrapper
      run: |
        rm -rf gradle/wrapper/gradle-wrapper.jar
        gradle wrapper --gradle-version 9.3.1

    - name: Build libhevtun
      id: cache-libhevtun
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/libs
        key: libhevtun-${{ runner.os }}-${{ hashFiles('.git/modules/hev-socks5-tunnel/HEAD') }}

    - name: Run compile script
      if: steps.cache-libhevtun.outputs.cache-hit != 'true'
      env:
        NDK_HOME: /usr/local/lib/android/sdk/ndk/28.2.13676358
      run: |
        chmod +x compile-hevtun.sh
        bash compile-hevtun.sh

    - name: Sync Libs
      run: |
        mkdir -p app/libs
        cp -r libs/* app/libs/

    - name: Download libv2ray
      run: |
        CURRENT_TAG=$(curl -s https://api.github.com/repos/unarto/Androidlibxraylitev26.1.23/releases/latest | jq -r .tag_name)
        curl -L "https://github.com/unarto/Androidlibxraylitev26.1.23/releases/download/$CURRENT_TAG/libv2ray.aar" -o app/libs/libv2ray.aar

    - name: Build APK (Arm64 Only)
      run: |
        echo "sdk.dir=${ANDROID_HOME}" > local.properties
        chmod +x gradlew
        # Kita panggil build cuma buat arm64
        ./gradlew assembleRelease -PabiFilters=arm64-v8a

    - name: Upload APK Arm64
      uses: actions/upload-artifact@v4
      with:
        name: sicepat-arm64-v8a
        path: app/build/outputs/apk/release/*.apk
