name: Copy dan Upload dari Repo

on:
  workflow_dispatch:

jobs:
  upload-repo-file:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Repo
        uses: actions/checkout@v4

      - name: Copy dari Folder Repo ke Folder Upload
        run: |
          mkdir -p hasil-upload
          # Ini bakal cari file di folder repo lu sendiri
          # Pastiin path ini sesuai sama posisi file lu di repo
          FILE=$(find . -name "*arm64-v8a*.apk" | head -n 1)
          
          if [ -n "$FILE" ]; then
            cp "$FILE" hasil-upload/sicepat-arm64.apk
            echo "File ditemukan di dalam repo: $FILE"
          else
            echo "File gak ada di repo, Cok. Coba cek lagi filenya udah lu push belum!"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sicepat-arm64-v8a
          path: hasil-upload/sicepat-arm64.apk
